//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial_Tutores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rol_BD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rol_BD()
        {
            this.Usuario_Rol_Servidor = new HashSet<Usuario_Rol_Servidor>();
        }
    
        public int IdRolBD { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdRolServidor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario_Rol_Servidor> Usuario_Rol_Servidor { get; set; }
        public virtual Rol_Servidor Rol_Servidor { get; set; }
    }
}
