//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial_Tutores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tipo_Usuario()
        {
            this.Rol_Servidor = new HashSet<Rol_Servidor>();
        }
    
        public int IdTipoUsuario { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> IdTutor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rol_Servidor> Rol_Servidor { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
