//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parcial_Tutores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario_Rol_BD
    {
        public int IdUsuarioRolBd { get; set; }
        public Nullable<int> IdUsuarioRolServidor { get; set; }
        public Nullable<int> IdUsuario { get; set; }
    
        public virtual Usuario_Rol_Servidor Usuario_Rol_Servidor { get; set; }
    }
}
